# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Project Viridian
email: kat@katcodes.dev
description: >- # this means to ignore newlines until "baseurl:"
  An upcoming LoGD Rewrite.
baseurl: "" # the subpath of your site, e.g. /blog
github_username: ViridianVille
show_downloads: false

# Build settings
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "mint"
locale: en-GB
url: "https://viridianville.github.io"

include: ["_pages"]

social:
  type: Organization
  name: Project Viridian
  links:
    - "http://viridianville.github.io"
    - "https://github.com/ViridianVille"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ViridianVille"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
category_archive:
  type: liquid
  path: /categories/

# Outputting
permalink: /posts/:year/:month/:day/:title:output_ext
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: GB # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
author:
  name: "The Project Viridian Team"
  avatar: "/assets/images/dab_dragon.png"
  bio: "We're **amazing** people."
  location: "Writing Code on the Internet"
